TextMessaging/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework.authtoken import views
from rest_framework_swagger.views import get_swagger_view

from .views import LoginView, LogoutView, ChangePasswordView

schema_view = get_swagger_view(title='Messaging APIs')


urlpatterns = [
                path('login/', LoginView.as_view(), name="sys_login"),
                path('logout/', LogoutView.as_view(), name="sys_logout"),
                path('change_password/', ChangePasswordView.as_view(), name="change_password"),
                path('api-token-auth/', views.obtain_auth_token),
                path('schema/', schema_view),
                path('admin/', admin.site.urls),
                path('api-auth/', include('rest_framework.urls')),
                path('', include('django.contrib.auth.urls')),
                path('sms/', include('sms.urls')),
                path('sms/api/', include('sms.rest_api.urls')),
              ]

sms/rest_api/urls.py
from django.urls import path, include

from rest_framework import routers

from sms.rest_api.views import *

router = routers.DefaultRouter()

router.register(r'users', UserViewSet)
router.register(r'applications', ApplicationViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('send/', SendMessage.as_view()),
    path('logs/', MessageLogs.as_view()),
    ]

sms/urls.py
from django.contrib import admin
from django.urls import path, include

from sms.views import *


urlpatterns = [
    path('users/', ListUsersView.as_view(), name='list_users'),
    path('user/add/', CreateUserView.as_view(), name='add_user'),
    path('user/<int:pk>/edit/', UpdateUserView.as_view(), name='update_user'),
    path('user/<int:pk>/delete/', DeleteUserView.as_view(), name='delete_user'),

    path('applications/', ListApplicationsView.as_view(), name='list_applications'),
    path('application/add/', CreateApplicationView.as_view(), name='add_application'),
    path('application/<int:pk>/edit/', UpdateApplicationView.as_view(), name='update_application'),
    path('application/<int:pk>/delete/', DeleteApplicationView.as_view(), name='delete_application'),
    
    path('', SMSView.as_view(), name='sms'),
    path('logs/', LogsView.as_view(), name='sms_logs'),
]

sms/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.dispatch import receiver
from django.db.models.signals import post_save

from rest_framework.authtoken.models import Token


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


class Application(models.Model):
    """
    Application model
    """
    name = models.CharField('Name', max_length=128, blank=False, null=False)
    app_admin = models.ForeignKey(settings.AUTH_USER_MODEL,  verbose_name = 'Owner Of Application', related_name='application',\
                                  on_delete=models.CASCADE)
    max_limit = models.PositiveIntegerField(default=0)
    status = models.CharField(max_length=10, choices=settings.STATUS_CHOICES, default='Active')
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = "Application"
        verbose_name_plural = "Applications"

    def __str__(self):
        return self.name

    def delete(self):
        """
        Delete application
        """
        self.status = 'Delete'
        self.save()


class TextMessageHistory(models.Model):
    """
    TextMessageHistory model
    """
    application = models.ForeignKey('Application', related_name='text_message_history', blank=True, null=True,\
                                    on_delete=models.SET_NULL)
    send_to = models.CharField('Send To', max_length=20, blank=False, null=False)
    text_message = models.TextField(null=False, blank=False)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return 'Sent to %s at %s' % (self.send_to, self.created_at)

sms/rest_api/views.py
import logging

from django.contrib.auth.models import User

from rest_framework.response import Response
from rest_framework import generics, status, viewsets, filters
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.permissions import IsAuthenticated
from sms.rest_api.permissions import IsAdminOrReadOnly
from sms.rest_api.serializers import *
from sms.utils import *


logger = logging.getLogger('message_log')


class UserViewSet(viewsets.ModelViewSet):
    """
    Work on user entity
    """
    queryset = User.objects.all()
    serializer_class = UserSerializer
    filter_backends = (filters.SearchFilter, filters.OrderingFilter, DjangoFilterBackend)
    search_fields = ('username', 'email')
    ordering_fields = ('id',)
    filter_fields = ('is_staff',)
    permission_classes = (IsAdminOrReadOnly,)

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())

        if not self.request.user.is_authenticated:
            return Response({'status': 400, 'message': 'You don\'t have permission to access users.'}, \
                            status=status.HTTP_400_BAD_REQUEST)

        if not self.request.user.is_staff:
            queryset = User.objects.filter(id=request.user.id)

        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        if instance != self.request.user and not self.request.user.is_staff:
            return Response({'status': 400, 'message': 'You don\'t have permission to access this user.'}, \
                            status=status.HTTP_400_BAD_REQUEST)
        serializer = self.get_serializer(instance)
        return Response(serializer.data)


class ApplicationViewSet(viewsets.ModelViewSet):
    """
    Work on application entity
    """
    queryset = Application.objects.all()
    serializer_class = ApplicationSerializer
    filter_backends = (filters.SearchFilter, filters.OrderingFilter, DjangoFilterBackend)
    search_fields = ('name',)
    ordering_fields = ('created_at', 'max_limit')
    filter_fields = ('status', 'app_admin')
    permission_classes = (IsAdminOrReadOnly,)

    def list(self, request, *args, **kwargs):
        queryset = Application.objects.exclude(status='Delete')

        if not self.request.user.is_authenticated:
            return Response({'status': 400, 'message': 'You don\'t have permission to access applications.'}, \
                            status=status.HTTP_400_BAD_REQUEST)

        if not self.request.user.is_staff:
            queryset = Application.objects.filter(app_admin=self.request.user.id)

        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        if instance.app_admin != self.request.user and not self.request.user.is_staff:
            return Response({'status': 400, 'message': 'You don\'t have permission to access this application.'}, \
                            status=status.HTTP_400_BAD_REQUEST)
        serializer = self.get_serializer(instance)
        return Response(serializer.data)


class SendMessage(generics.CreateAPIView):
    """
    Send Message.
    """
    serializer_class = TextMessageSerializer
    permission_classes = (IsAuthenticated,)

    def post(self, request, format=None):
        try:
            serializer = TextMessageSerializer(data=request.data)
            if serializer.is_valid():
                if 'app_id' in serializer.data:
                    app = Application.objects.get(id=int(serializer.data['app_id']))
                    if not is_application_or_system_admin(request, app.id):
                        return Response({'status': 400,
                                         'message': 'You don\'t have permission to send sms for this application.'},\
                                        status=status.HTTP_400_BAD_REQUEST)

                    if is_application_expire(app.id):
                        return Response({'status': 400, 'message': 'Selected application is expired'},\
                                        status=status.HTTP_400_BAD_REQUEST)
                    message_log = send_sms(serializer.data['send_to'], serializer.data['message'])
                    message_log.application = app
                    message_log.save()
                else:
                    send_sms(serializer.data['send_to'], serializer.data['message'])
                return Response({'status': 201, 'message': 'SMS sent successfully'}, status=status.HTTP_201_CREATED)
            logger.error("Fail to send sms")
            return Response({'status': 400, 'message': 'Fail to send SMS'}, status=status.HTTP_400_BAD_REQUEST)
        except Exception as e:
            logger.error("Error occured while sending sms "+str(e))
            return Response({'status': 400, 'message': str(e)}, status=status.HTTP_400_BAD_REQUEST)


class MessageLogs(generics.ListAPIView):
    """
    SMS Logs.
    """
    queryset = TextMessageHistory.objects.all()
    serializer_class = TextMessageHistorySerializer
    filter_backends = (filters.SearchFilter, filters.OrderingFilter, DjangoFilterBackend)
    search_fields = ('text_message',)
    ordering_fields = ('created_at',)
    filter_fields = ('application', 'send_to')
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        """
        Return the list of items for this view.
        """
        queryset = TextMessageHistory.objects.all()
        if not self.request.user.is_staff:
            queryset = TextMessageHistory.objects.filter(application__app_admin=self.request.user)
        return queryset

sms/views.py
import plivo
import logging

from django.conf import settings
from django.contrib.auth.models import User
from django.views import View
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.generic import ListView
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect

from sms.models import *
from sms.utils import *


logger = logging.getLogger('message_log')


class ListUsersView(LoginRequiredMixin, ListView):
    """
    List Users
    """
    model = User
    queryset = User.objects.all()
    template_name = 'user_list.html'

    def get_queryset(self):
        """
        Return the list of items for this view.
        """
        queryset = User.objects.all()
        if not self.request.user.is_staff:
            queryset = User.objects.filter(id=self.request.user.id)
        return queryset


class CreateUserView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Create new user
    """
    model = User
    fields = ['username', 'password', 'email', 'is_staff']
    template_name = 'user_form.html'
    success_message = "%(username)s was created successfully"
    success_url = reverse_lazy('list_users')

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        form = self.get_form()
        if form.is_valid():
            user = form.save()
            user.set_password(request.POST['password'])
            user.save()
        else:
            logger.error(form.errors)
            messages.error(request, form.errors)
            return redirect('add_user')
        messages.success(request, "{}, user added successfully.".format(user.username))
        return HttpResponseRedirect(reverse('list_users'))


class UpdateUserView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    Update existing user
    """
    model = User
    fields = ['username', 'password', 'email', 'is_staff']
    template_name = 'user_form.html'
    success_message = "%(username)s was updated successfully"
    success_url = reverse_lazy('list_users')


class DeleteUserView(LoginRequiredMixin, DeleteView):
    """
    Delete existing user
    """
    model = User
    template_name = 'user_confirm_delete.html'
    success_url = reverse_lazy('list_users')


class ListApplicationsView(LoginRequiredMixin, ListView):
    """
    List applications
    """
    model = Application
    queryset = Application.objects.exclude(status='Delete')
    template_name = 'application_list.html'

    def get_queryset(self):
        """
        Return the list of items for this view.
        """
        queryset = Application.objects.exclude(status='Delete')
        if not self.request.user.is_staff:
            queryset = Application.objects.filter(app_admin=self.request.user.id)
        return queryset


class CreateApplicationView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Create new application
    """
    model = Application
    fields = ['name', 'app_admin', 'max_limit', 'status']
    template_name = 'application_form.html'
    success_message = "%(name)s was created successfully"
    success_url = reverse_lazy('list_applications')


class UpdateApplicationView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    Update existing application
    """
    model = Application
    fields = ['name', 'max_limit', 'status']
    template_name = 'application_form.html'
    success_message = "%(name)s was updated successfully"
    success_url = reverse_lazy('list_applications')


class DeleteApplicationView(LoginRequiredMixin, DeleteView):
    """
    Delete existing application
    """
    model = Application
    template_name = 'application_confirm_delete.html'
    success_url = reverse_lazy('list_applications')


class SMSView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    send SMS
    """
    model = TextMessageHistory
    fields = ['application', 'send_to', 'text_message']
    template_name = 'sms_form.html'
    success_message = "SMS sent successfully"
    success_url = reverse_lazy('sms')

    def get_context_data(self, **kwargs):
        context = super(SMSView, self).get_context_data(**kwargs)
        if self.request.user.is_staff:
            context['form'].fields['application'].queryset = Application.objects.exclude(status='Delete')
        else:
            context['form'].fields['application'].queryset = Application.objects.filter(app_admin=self.request.user)
        return context

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """

        try:
            if request.POST['application']:
                if is_application_expire(request.POST['application']):
                    messages.error(request, "Selected application is expired.")
                    return redirect('sms')

            form = self.get_form()
            if form.is_valid():
                client = plivo.RestClient(settings.PLIVO_AUTH_ID, settings.PLIVO_AUTH_TOKEN)
                client.messages.create(src=settings.SENDER_NUMBER, dst=request.POST['send_to'],\
                                   text=request.POST['text_message'], )
                form.save()
                messages.success(request, "Successfully SMS sent.")

        except Exception as e:
            logger.error("Error occured while sending sms "+str(e))
            messages.error(request, "Error occured while sending sms.")
        return redirect('sms')


class LogsView(LoginRequiredMixin, ListView):
    """
    SMS logs
    """
    model = TextMessageHistory
    queryset = TextMessageHistory.objects.all()
    template_name = 'sms_history.html'

    def get_queryset(self):
        """
        Return the list of items for this view.
        """
        queryset = TextMessageHistory.objects.all()
        if not self.request.user.is_staff:
            queryset = TextMessageHistory.objects.filter(application__app_admin=self.request.user)
        return queryset

sms/templates/application_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% block body %}
     <form data-parsley-validate class="form-horizontal form-label-left" method="post">
         {% csrf_token %}
          <div class="form-group">
              <h4>Are you sure want to delete "{{ object.name }}" application? </h4>
          </div>
         <div class="ln_solid"></div>
          <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
              <input type="submit" value="Submit" class="btn btn-primary" />
              <a href="{% url 'list_applications' %}" class="btn btn-info">Cancel</a>
            </div>
          </div>
     </form>
{% endblock %}

sms/templates/application_form.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block body %}
       <div class="page-title">
            <div class="title_left">
                <h3>Application</h3>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_content">
                            <br />
                            <section class="content">
                              <div class="row">
                                <div class="col-xs-12">
                                  <div class="">
                                        <div class="box-header" >
                                          {% if messages %}
                                            <ul class="messages">
                                              {% for message in messages %}
                                                <div class="alert alert-{{ message.tags }} alert-dismissable">
                                                  <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                                                {{ message }}
                                                </div>
                                              {% endfor %}
                                            </ul>
                                          {% endif %}
                                        </div>
                                    <!-- /.box-header -->
                                    <div class="box-body">
                                        <form method="post" enctype = "multipart/form-data" >
                                            {% csrf_token %}
                                            {{ form.as_p }}
                                          <div class="ln_solid"></div>
                                          <div class="form-group">
                                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                              <a href="{% url 'list_applications' %}" class='btn btn-primary' >Cancel</a>
                                              <button class="btn btn-primary" type="reset">Reset</button>
                                              <input type="submit" class="btn btn-success"/>
                                            </div>
                                          </div>
                                        </form>
                                    </div>
                                    <!-- /.box-body -->
                                  </div>
                                  <!-- /.box -->
                                </div>
                                <!-- /.col -->
                              </div>
                              <!-- /.row -->
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

{% block static %}
<script>
  $(document).ready(function(){
   $("#id_name").addClass( "form-control" );
   $("#id_app_admin").addClass( "form-control" );
   $("#id_max_limit").addClass( "form-control" );
   $("#id_status").addClass( "form-control" );
    });
</script>
{% endblock %}

sms/templates/application_list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block body %}
       <div class="page-title">
            <div class="title_left">
                <h3>Applications</h3>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="">
                            {% if request.user.is_staff %}
                            <ul class="list-inline pull-right clearfix controls">
                                <li>
                                    <a class="btn btn-primary download-excel" href="{% url 'add_application' %}"> <i class="fa fa-plus"></i> Create New Application</a>
                                </li>
                            </ul>
                            {% endif %}
                            <div class="clearfix">
                            </div>
                        </div>
                        <div class="box-header" >
                          {% if messages %}
                            <ul class="messages">
                              {% for message in messages %}
                                <div class="alert alert-{{ message.tags }} alert-dismissable">
                                  <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                                {{ message }}
                                </div>
                              {% endfor %}
                            </ul>
                          {% endif %}
                        </div>
                        <div class="x_content">
                            <br />
                            <div class="table-responsive">
                                <table id="application_table" class="cell-border">
                                    <thead>
                                    <tr>
                                      <th>Application Id</th>
                                      <th>Name</th>
                                      <th>Max Limit</th>
                                      <th>Status</th>
                                      <th>Created At</th>
                                     {% if request.user.is_staff %}
                                      <th class="no-sort">Action</th>
                                     {% endif %}
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for application in application_list %}
                                      <tr>
                                        <td>{{ application.id }}</td>
                                        <td>{{ application.name }}</td>
                                        <td>{{ application.max_limit }}</td>
                                        <td>{{ application.status }}</td>
                                        <td>{{ application.created_at }}</td>
                                        {% if request.user.is_staff %}
                                        <td>
                                          <a class="fa fa-pencil-square-o" href="{% url 'update_application' application.id %}"></a>
                                          <a class="fa fa-times client_delete_icon" href="{% url 'delete_application' application.id %}" obj_name='' style="padding-left:50px;"></a>
                                        </td>
                                        {% endif %}
                                      </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

{% block static %}
<script>
  $(document).ready(function(){
  $('#application_table').DataTable();
  });
</script>
{% endblock %}

sms/templates/sms_form.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block body %}
<div class="page-title">
    <div class="title_left">
        <h3>Send SMS</h3>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    <br />
                    <section class="content">
                      <div class="row">
                        <div class="col-xs-12">
                          <div class="">
                            <div class="box-header">
                              {% if messages %}
                                <ul class="messages alert alert-danger">
                                  {% for message in messages %}
                                    {{ message }}
                                  {% endfor %}
                                </ul>
                              {% endif %}
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                              <form id="client-form" data-parsley-validate class="form-horizontal form-label-left" enctype="multipart/form-data" method="post" action="{% url 'sms' %}">
                                  {% csrf_token %}
                              <!--<div class="form-group">-->
                                  <!--<label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_mobile">Send To <span class="required" style='color:red;'>*</span></label>-->
                                  <!--<div class="col-md-6 col-sm-6 col-xs-12">-->
                                  <!--<input type="text" name="mobile" maxlength="16" required id="id_mobile" class="form-control col-md-7 col-xs-12"/></p>-->
                                <!--</div>-->
                              <!--</div>-->
                              <!--<div class="form-group">-->
                                  <!--<label class="control-label col-md-3 col-sm-3 col-xs-12" for="id_message">Message <span class="required" style='color:red;'>*</span></label>-->
                                  <!--<div class="col-md-6 col-sm-6 col-xs-12">-->
                                       <!--<textarea name="message" maxlength="128" required id="id_message" class="form-control col-md-7 col-xs-12"></textarea></p>-->
                                <!--</div>-->
                              <!--</div>-->
                                  {{ form.as_p }}
                              <div class="ln_solid"></div>
                              <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                  <button class="btn btn-primary" type="reset">Reset</button>
                                  <input type="submit" class="btn btn-success"/>
                                </div>
                              </div>
                            </form>
                            </div>
                            <!-- /.box-body -->
                          </div>
                          <!-- /.box -->
                        </div>
                        <!-- /.col -->
                      </div>
                      <!-- /.row -->
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block static %}
<script>
  $(document).ready(function(){
   $("#id_application").addClass( "form-control" );
   $("#id_send_to").addClass( "form-control" );
   $("#id_text_message").addClass( "form-control" );
    });
</script>
{% endblock %}

sms/templates/sms_history.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block body %}
       <div class="page-title">
            <div class="title_left">
                <h3>Logs of SMS</h3>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="box-header" >
                          {% if messages %}
                            <ul class="messages">
                              {% for message in messages %}
                                <div class="alert alert-{{ message.tags }} alert-dismissable">
                                  <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                                {{ message }}
                                </div>
                              {% endfor %}
                            </ul>
                          {% endif %}
                        </div>
                        <div class="x_content">
                            <br />
                            <div class="table-responsive">
                                <table id="log_table" class="cell-border">
                                    <thead>
                                    <tr>
                                      <th>Log Id</th>
                                      <th>Application Name</th>
                                      <th>Sent To</th>
                                      <th>Message</th>
                                      <th>Sent At</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for log in textmessagehistory_list %}
                                      <tr>
                                        <td>{{ log.id }}</td>
                                        <td>{{ log.application.name }}</td>
                                        <td>{{ log.send_to }}</td>
                                        <td>{{ log.text_message }}</td>
                                        <td>{{ log.created_at }}</td>
                                      </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

{% block static %}
<script>
  $(document).ready(function(){
  $('#log_table').DataTable();
  });
</script>
{% endblock %}